# Generated by Django 5.0.6 on 2024-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='images/slides/')),
                ('slide_title', models.CharField(max_length=200)),
                ('slide_subtitle', models.CharField(max_length=200)),
                ('side_image', models.ImageField(upload_to='images/')),
                ('side_title', models.CharField(max_length=200)),
                ('side_subtitle', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
